mission_file_name: "mission_depth_only.xml"

physics:
  # Float
  m: 18.0
  piston_ref_eq: 2100

driver:
  thruster:
    thruster_left_pin: 0
    thruster_right_pin: 1
    invert_left: false
    invert_right: true

  imu:
    ellipsoid_offset: [0, 0, 0]
    ellipsoid_matrix0: [1, 0, 0]
    ellipsoid_matrix1: [0, 1, 0]
    ellipsoid_matrix2: [0, 0, 1]

    accel_min: [-1.08, -0.92, -1.0]
    accel_max: [1.04,  1.01,  1.11]

    gyro_bias: [-2.36e-05, 4.64e-07, 2.22e-05]
